index:
    path: /
    controller: App\Controller\RegistrationController::login
register:
    path: /register
    controller: App\Controller\RegistrationController::register   
home:
    path: /home
    controller: App\Controller\DefaultController::index    