index:
    path: /
    controller: App\Controller\DefaultController::index
register:
    path: /register
    controller: App\Controller\RegistrationController::register   
logout:
    path: /logout
    controller: App\Controller\RegistrationController::logout    
home:
    path: /home
    controller: App\Controller\DefaultController::home    
login:
    path: /login
    controller: App\Controller\DefaultController::login        